# Generated by Django 3.2 on 2023-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
